# 此文件用于配置分析器，分析器会静态检查 Dart 代码中的错误、警告和 lint。
#
# 分析器发现的问题会显示在支持 Dart 的 IDE 界面中（https://dart.dev/tools#ides-and-editors）。
# 也可以在命令行中运行 `flutter analyze` 来执行分析。

# 下方这一行会启用 Flutter 应用、包和插件的一组推荐 lint，帮助保持良好的编码习惯。
include: package:flutter_lints/flutter.yaml

linter:
  # 下面的部分可用于自定义本项目启用的 lint 规则，
  # 例如关闭上方 `package:flutter_lints/flutter.yaml` 中包含的规则，或启用更多规则。
  # 所有可用 lint 及其文档可在 https://dart.dev/lints 查看。
  #
  # 如果不想针对整个项目关闭某条 lint，也可以在单行代码上使用
  # `// ignore: name_of_lint`，或在单个 Dart 文件中使用
  # `// ignore_for_file: name_of_lint` 来忽略相应规则。
  rules:
    # avoid_print: false  # 取消注释可禁用 `avoid_print` 规则
    # prefer_single_quotes: true  # 取消注释可启用 `prefer_single_quotes` 规则

# 关于此文件的更多信息，请参见：
# https://dart.dev/guides/language/analysis-options
